#!/usr/bin/env bash
#
#  firstislamiccoind The firstislamiccoin more server.
#
#
# chkconfig: 345 80 20
# description: firstislamiccoind
# processname: firstislamiccoind
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/firstislamiccoind, see below
if [ -f /etc/sysconfig/firstislamiccoind ]; then
        . /etc/sysconfig/firstislamiccoind
fi

RETVAL=0

prog=bitcoind
# you can override the lockfile via BITCOIND_LOCKFILE in /etc/sysconfig/firstislamiccoind
lockfile=${BITCOIND_LOCKFILE-/var/lock/subsys/firstislamiccoind}

# bitcoind defaults to /usr/bin/firstislamiccoind, override with BITCOIND_BIN
bitcoind=${BITCOIND_BIN-/usr/bin/firstislamiccoind}

# bitcoind opts default to -disablewallet, override with BITCOIND_OPTS
bitcoind_opts=${BITCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $bitcoind $bitcoind_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
