.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. firstislamiccoin_qt test_firstislamiccoin_qt
clean: FORCE
	$(MAKE) -C .. firstislamiccoin_qt_clean test_firstislamiccoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_firstislamiccoin_qt_check
firstislamiccoin-qt firstislamiccoin-qt.exe: FORCE
	 $(MAKE) -C .. firstislamiccoin_qt
apk: FORCE
	$(MAKE) -C .. firstislamiccoin_qt_apk
